package pojos;
// Generated Apr 30, 2017 5:24:23 PM by Hibernate Tools 4.3.1



/**
 * ContactPhones generated by hbm2java
 */
public class ContactPhones  implements java.io.Serializable {


     private Integer id;
     private Contact contact;
     private String phone;

    public ContactPhones() {
    }

    public ContactPhones(Contact contact, String phone) {
       this.contact = contact;
       this.phone = phone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Contact getContact() {
        return this.contact;
    }
    
    public void setContact(Contact contact) {
        this.contact = contact;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


