package pojos;
// Generated Apr 30, 2017 5:24:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String firstName;
     private String lastName;
     private String email;
     private byte[] image;
     private Set contactPhoneses = new HashSet(0);

    public Contact() {
    }

	
    public Contact(User user, String firstName) {
        this.user = user;
        this.firstName = firstName;
    }
    public Contact(User user, String firstName, String lastName, String email, byte[] image, Set contactPhoneses) {
       this.user = user;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.image = image;
       this.contactPhoneses = contactPhoneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Set getContactPhoneses() {
        return this.contactPhoneses;
    }
    
    public void setContactPhoneses(Set contactPhoneses) {
        this.contactPhoneses = contactPhoneses;
    }




}


