package pojos;
// Generated Apr 30, 2017 5:24:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String phone;
     private String password;
     private String firstName;
     private String lastName;
     private String email;
     private byte[] image;
     private Set contacts = new HashSet(0);
     private Set userPhoneses = new HashSet(0);

    public User() {
    }

	
    public User(String phone, String password, String firstName) {
        this.phone = phone;
        this.password = password;
        this.firstName = firstName;
    }
    public User(String phone, String password, String firstName, String lastName, String email, byte[] image, Set contacts, Set userPhoneses) {
       this.phone = phone;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.image = image;
       this.contacts = contacts;
       this.userPhoneses = userPhoneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Set getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set contacts) {
        this.contacts = contacts;
    }
    public Set getUserPhoneses() {
        return this.userPhoneses;
    }
    
    public void setUserPhoneses(Set userPhoneses) {
        this.userPhoneses = userPhoneses;
    }




}


