package pojos;
// Generated Apr 30, 2017 5:24:23 PM by Hibernate Tools 4.3.1



/**
 * UserPhones generated by hbm2java
 */
public class UserPhones  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String phone;

    public UserPhones() {
    }

    public UserPhones(User user, String phone) {
       this.user = user;
       this.phone = phone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


